### ISSUE TITLE
Importance of Target vulnerability for binding kinetics

### ISSUE THREAD

**Issue by vaibhavadixit** [seekrcentral/seekr2#14]
Dear Seekr2 team,
I have a pharmacology and drug discovery-oriented question regarding binding kinetics.
I hope this is appropriate for this forum because I'm guessing that the developers are working on similar projects and would have made decisions on similar lines.

So here is the question.
I've learned from some literature that the importance of kinetic selectivity in drug discovery also depends on the target vulnerability (Peter Tonge ACS  Chem. Neurosci.2018, 9, 29−39., DOI:10.1021/acschemneuro.7b00185).
In short, for targets that have a low vulnerability (high turnover or other means), kinetic selectivity is less likely to be of major importance in drug design and candidate selection.  Only for high vulnerability targets, kinetic selectivity would play a role in drug efficacy, and thus using seerk2-like methods for estimation of kon, koff and kinetic Kd makes sense.

Especially, I want to understand if it would make sense to run complicated SEEKR2 calculations in the absence of information on target vulnerability.  Because for a given target if only the thermodynamic selectivity plays a role in drug efficacy then binding kinetics assessment is not expected to correlate with selectivity and efficacy (even if predictions agree with measurements of kon/koff from SPR experiments or other methods).

Thus I'm curious to know if you are considering these aspects while you are making predictions on kon/koff for different targets of interest.
Looking forward to valuable suggestions and comments from this group.
Thank you and best regards.
Dr. Vaibhav A. Dixit

**Comment by lvotapka** [comment]
I'm gathering my thoughts about this - I'll likely answer after the July 4th holiday...

**Comment by lvotapka** [comment]
This is an interesting question.

1. In essence, you are stating that kinetics will be most important to consider for high-vulnerability targets, since kinetic selectivity and prolonged effects will only be useful for targets with high vulnerability. In contrast, low-vulnerability targets will more quickly recover from treatment, regardless of the binding/unbinding kinetics. Therefore, for low-vulnerability targets, we are forced to consider the thermodynamics as being of primary importance when considering selectivity and efficacy.

2. You express doubt that SEEKR2 will be useful for a target unless one can confirm that it is a high-vulnerability target.

Here are my answers:

First, I'd like to point out that SEEKR2 can obtain estimates of thermodynamics quantities in addition to kinetics (the K_D is a thermodynamic quantity), so SEEKR2 is equally likely to be useful for either high- or low-vulnerability targets. In addition, SEEKR2 doesn't just provide k_on, k_off, and K_D, but also molecular-level details about the binding process. (We are actively working on tools to leverage SEEKR2 results to extract molecular details of binding, by the way.)

Assertion 1 seems valid. However, I'm not sure how often the vulnerability of a target is measured experimentally, or whether it can be effectively modeled computationally. In theory, one could perform an experiment and make plots similar to figure 4 in Tonge 2018 to obtain the vulnerability, But then, at least for that inhibitor-target pair, one has already measured the kinetics, and SEEKR2 would not add any additional kinetics information. However, once the target's vulnerability is known, one could use that knowledge when discovering new inhibitors. It would make sense for a pharma company, after identifying a target, to measure that target's vulnerability in order to decide whether to focus on favorable kinetics or thermodynamics.

I don't believe that assertion 2 is valid, however, because SEEKR2 can obtain thermodynamics of binding, as well as kinetics. However, without knowledge of the vulnerability of the target, one may not know whether to focus on favorable kinetics or thermodynamics of an inhibitor.

I'd be interested to continue discussing and to hear any further thoughts on the matter.

**Comment by lvotapka** [comment]
I'm going to close this issue for now.
