### ISSUE TITLE
Import Error During Installation

### ISSUE THREAD

**Issue by mukherjeesutanu** [seekrcentral/seekr2#29]
Hi,

I'm getting the following error while trying to import "seekr2plugin", 

====================================== short test summary info ======================================
ERROR  - ImportError: libOpenMM.so.7.7: cannot open shared object file: No such file or directory
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================= 1 error in 0.77s ==========================================

Please let me know how to get rid of this error.

Sincerely,
Sutanu

**Comment by lvotapka** [comment]
If the program was working before, this most likely happened because OpenMM 8.0 was installed on top of an existing OpenMM 7.7 installation, or possibly because a SEEKR2 plugin installation from source had a conda-forge installation made overtop it. I'd suggest a clean reinstall of OpenMM and the SEEKR2 plugin, on a fresh conda environment if possible.

If this is happening on a fresh installation from source, make sure you are setting LD_LIBRARY_PATH to point to the OpenMM libraries:

```
export LD_LIBRARY_PATH="/path/to/bin/openmm/lib:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="/path/to/bin/openmm/lib/plugins:$LD_LIBRARY_PATH"
```

**Comment by lvotapka** [comment]
I'm assuming the issue was resolved.
