### ISSUE TITLE
Facing problem in analyze.py step

### ISSUE THREAD

**Issue by MissRaut** [seekrcentral/seekr2#32]
Hello, Janvi here,  I have performed seekr2 calculation and got following error at analyze step : 

"     The center of masses of atom group1 and atom group2 were found to be 1.0000 nm apart. This distance falls 
       outside of the milestone boundary at 1.0000 nm.
        CHECK FAILURE: The MMVT trajectory(ies) for anchor 7 do not lie within the anchor boundaries. This could be 
        caused by incorrect modification of files or the model.xml file, or possibly a bug.
         One or more fatal post-simulation checks failed. It is highly recommended that you address and correct each of 
         these problems. However, you can force SEEKR to skip these checks by using the --skip_checks (-s) argument on 
        analyze.py. "   can you suggest ?

**Comment by lvotapka** [comment]
If this is at the analyze.py step, you can probably safely skip this particular check by including the "-s" argument to analyze.py - this problem shouldn't affect anything.

**Comment by MissRaut** [comment]
yes , sir I already did so but then my results for Kon Koff values are differing alot from values estimated in litreture.

**Comment by MissRaut** [comment]
also kon_convergence plot and free energy profile has generated but not getting koff_convergence plot ?

**Comment by lvotapka** [comment]
This may be a long answer. To address your first point, that SEEKR2 results are not closely matched to literature values, this may be caused by any of a large number of possible reasons:

1. Something is wrong with your inputs. This could be a) bad starting structures, or structures that were not properly minimized or equilibrated, or b) you are not adequately modeling the physical/chemical system represented in the literature (incorrect salt concentrations, temperatures, wrong protonation state of small molecule or receptor sidechains, wrong mutants, missing loops, wrong monomer/polymer state, etc.), c) you may not be using the optimal SEEKR inputs (insufficient lengths of simulations, bad choice of collective variables, bad milestone placements). To address this possibility, you should get an MD expert (or be an MD expert yourself) to look at all your MD structures, inputs, etc. You should also be sure to use the correct SEEKR inputs and protocols. One of our best papers that defines most or all of the best SEEKR2 inputs, as we currently believe them to be, can be found at: https://pubs.acs.org/doi/full/10.1021/acs.jcim.2c01589. It's possible that better results can be obtained with longer SMD simulations, or possibly more sampling in each SEEKR2 milestone. The problem is most likely one of these things, and you should spend a large and significant amount of time making sure that something isn't wrong in this category. Do not skip this step.

2. Once you have exhaustively checked that nothing is wrong with the first point above, it's possible that the problem is coming from inadequate forcefield parametrization of the ligand and binding site. We currently have developed a tool called QMrebind (https://github.com/anandojha/qmrebind.git) to address systems with this problem, and we have had some luck getting better residence times for the HSP90 system. Our manuscript for this tool is under review, but you can find our archived manuscript here: https://chemrxiv.org/engage/chemrxiv/article-details/64d2d5bd69bfb8925a9adabf. In relatively rare cases, however, even reparametrization didn't improve k-off/k-on calculations, as we reported in the manuscript.

3. Lastly, which is a current area of research for us, it's possible that the normal COM-COM collective variable, in combination with SMD, does not adequately describe the binding pathway, or does not allow us to generate good starting structures for our Voronoi cells. As I said, this is an active area of research, and if this is indeed the problem, you will need to wait until we develop better methods for addressing this problem. In my experience, this problem seems to be fairly rare, and the COM-COM CV combined with SMD seems to work well for nearly every system I've encountered.

Without more specific details about your system (where you obtained the structures, your preparation procedure, your settings and inputs, and other such details) I cannot say what may be going wrong. You will need to do a careful investigation if you hope to obtain kinetics that match those reported in literature.

I will look into the lack of k-off convergence plots and make sure something isn't going wrong there...

**Comment by MissRaut** [comment]
Sure , Thank you for your responce sir, i'll go through the references you have suggested and will let you know .

**Comment by lvotapka** [comment]
I just pushed a bugfix that should cause the k-off convergence plots to generate correctly.

Good luck with your investigations into the cause of the inaccuracy you observe.

**Comment by MissRaut** [comment]
ohh, Thank you so much Mr. Lane.
