### ISSUE TITLE
Question/Issue: Index Error running BD-Milestone

### ISSUE THREAD

**Issue by bensebaer** [seekrcentral/seekr2#7]
Hi Lane,
I come across another issue running the BD-simulations in seekr2. First, I would like to ask if running the BD-milestone in seekr2 requires a converged MD-part?

Anyway, I have the following issue running the BD-milestone after the b_surface simulations are finished. I am not sure, if the lower error is independent from the MissingStatiscsError or a consequence of the "-s" option not working in this case.

Running command:
python ~/Software/seekr2/seekr2/run.py any_bd model.xml -s

Output:
Traceback (most recent call last):
  File "/home/bensebaer/Software/conda/envs/SEEKR2/lib/python3.8/site-packages/seekr2-0+untagged.144.ge74fc0f.dirty-py3.8.egg/seekr2/modules/common_converge.py", line 142, in analyze_kinetics
    sufficient_statistics = analysis.check_extraction()
  File "/home/bensebaer/Software/conda/envs/SEEKR2/lib/python3.8/site-packages/seekr2-0+untagged.144.ge74fc0f.dirty-py3.8.egg/seekr2/analyze.py", line 301, in check_extraction
    result = self.mmvt_check_anchor_stats(silent)
  File "/home/bensebaer/Software/conda/envs/SEEKR2/lib/python3.8/site-packages/seekr2-0+untagged.144.ge74fc0f.dirty-py3.8.egg/seekr2/analyze.py", line 228, in mmvt_check_anchor_stats
    raise common_analyze.MissingStatisticsError(
seekr2.modules.common_analyze.MissingStatisticsError: Anchor(s) [1, 3] are missing sufficient statistics. Consider running simulations of anchor(s) [1, 3] for longer time scales or readjust anchor locations to make transitions more frequent. You may skip this check with the --skip_checks (-s) option.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bensebaer/Software/seekr2/seekr2/run.py", line 742, in <module>
    run(model, instruction, min_total_simulation_length, 
  File "/home/bensebaer/Software/seekr2/seekr2/run.py", line 553, in run
    bd_milestone_info_to_run = choose_next_simulation_browndye2(
  File "/home/bensebaer/Software/seekr2/seekr2/run.py", line 50, in choose_next_simulation_browndye2
    data_sample_list = converge.converge(model)
  File "/home/bensebaer/Software/conda/envs/SEEKR2/lib/python3.8/site-packages/seekr2-0+untagged.144.ge74fc0f.dirty-py3.8.egg/seekr2/converge.py", line 29, in converge
    = common_converge.check_milestone_convergence(
  File "/home/bensebaer/Software/conda/envs/SEEKR2/lib/python3.8/site-packages/seekr2-0+untagged.144.ge74fc0f.dirty-py3.8.egg/seekr2/modules/common_converge.py", line 333, in check_milestone_convergence
    k_on, k_off, N_ij, R_i = analyze_kinetics(
  File "/home/bensebaer/Software/conda/envs/SEEKR2/lib/python3.8/site-packages/seekr2-0+untagged.144.ge74fc0f.dirty-py3.8.egg/seekr2/modules/common_converge.py", line 164, in analyze_kinetics
    data_sample.parse_browndye_results()
  File "/home/bensebaer/Software/conda/envs/SEEKR2/lib/python3.8/site-packages/seekr2-0+untagged.144.ge74fc0f.dirty-py3.8.egg/seekr2/modules/common_analyze.py", line 470, in parse_browndye_results
    browndye_run_compute_rate_constant(os.path.join(
  File "/home/bensebaer/Software/conda/envs/SEEKR2/lib/python3.8/site-packages/seekr2-0+untagged.144.ge74fc0f.dirty-py3.8.egg/seekr2/modules/common_analyze.py", line 241, in browndye_run_compute_rate_constant
    dest = int(name[1])
IndexError: list index out of range

#I also checked the contents of name[] and apparently, name[1] is empty and name[0]=['7'].

#From the results1.xml file:
  <reactions>
    <n_trajectories> 1000000 </n_trajectories>
    <stuck> 0 </stuck>
    <escaped> 999944 </escaped>
    <completed>
      <name> 7 </name>
      <n> 56 </n>
    </completed>
  </reactions>

Thank you very much for your help
Jens

**Comment by lvotapka** [comment]
Hi Jens,

To answer your first question, you should be able to run MD or BD in any order.

So this looks like some sort of bug. Are you able to send me a tarball of the files that generate this error?

And you're welcome, I'm happy to help you get your systems running.

**Comment by bensebaer** [comment]
Hi Lane,
thank you for your help. I created a tarball with the seekr-root directory and the seekr-input file. Here is a link to the tarball in my OneDrive. Please tell me if it doesn't work.

Link:  https://1drv.ms/u/s!AldqnraKFN73ga04uohmv8jjoX0L7Q

**Comment by lvotapka** [comment]
Thank you, Jens. I was able to download it. I'll take a look at this and get back to you as soon as I get to the bottom of the issue.

**Comment by lvotapka** [comment]
Jens, would you also mind sending the equil/, apbs/ and SMD1/ directories as tarballs, just so that I can debug the seekr2 preparation scripts with your input structures?

**Comment by bensebaer** [comment]
Yes of course, sorry for that. 

Here:
https://1drv.ms/u/s!AldqnraKFN73ga03I_XiBrQe9qGp8w?e=9OsOzB

**Comment by lvotapka** [comment]
Hi Jens,

Thanks for sending these files.

It turns out that this problem you encountered was caused because about two or three weeks ago, I made a pretty big change in how SEEKR2 handles BD simulations, and I changed quite a few things about file formats, etc. It looks like you had, by chance, downloaded and ran some simulations using the older version of SEEKR2, and when you updated and tried to run additional simulations, the files were no longer compatible with the software. If you do the following steps, you should be able to complete your simulations.

1. First, you'll need to delete the directories "b_surface" and "bd_milestone_0" and all their contents because your BD simulations will have to be redone.
2. Then, re-run the prepare.py script on your input XML file. This should keep all your MD simulations intact.

Now, you should be good to go, but I've been working on some code changes that will prevent this error in the future. But if you follow these steps they should work with the existing code. But if you want to wait until I push the latest code, you can do that too.

By the way, I noticed that you're using 496 threads for the BD stage. This seems like an unusually large number of cores to use for a shared memory process like Browndye. Are you sure that this is correct?

**Comment by bensebaer** [comment]
Hi Lane,
thank you very much for your help. Yes you are right, I was using an older code when preparing the input files. I am not sure if I could run the bd-milestone using the older code but I will try regenerate the input and repeat the simulations with the newer code as you suggested.

Regarding the high CPU-count. It is certainly not an efficient way of performing the simulations. I was trying to speed up the BD-part during times with low occupancy at our cluster. I see some improvement using multiple nodes (infiniband connected) however, generally it is not worth it.

**Comment by lvotapka** [comment]
Hi Jens,

You're welcome, and all that sounds good to me.

I did just push the latest version of the seekr2 code, so I'd recommend pulling and installing with "python setup.py install" before running the prepare.py and run.py scripts. Good luck.

**Comment by bensebaer** [comment]
Hi Lane,
thank you for the update. I updated the code and restarted the simulations. I hope you will not update the code to a state which requires the MD-part to be rerun :D

Anyway, I had another question unrelated to this issue. But I was wondering how you were choosing the ion-radii for the BD-simulations?
I have seen you were citing a paper for the radii of TRIS in the original SEEKR publication but I was not able to understand how you calculated these.

Publication: 
Schindler, P.; Robinson, R. A.; Bates, R. G. Solubility of Tris(Hydroxymethyl)Aminomethane in Water-Methanol Solvent Mixtures and Medium Effects in Dissociation of Protonated Base. J. Res. Natl. Bur. Stand., Sect. A 1968, 72A (2), 141−148.

**Comment by lvotapka** [comment]
Hey Jens,

Yes, the ion radii for the BD simulations are used to determine the solvent accessibility, particularly in the APBS calculations. In the past, we had been using radii from example APBS input files, and also from publications, when radii or diffusion coefficients were available (as in the case of Tris, as you mentioned). As time has gone on, I have realized that the best radii would probably come from Born radii (since they represent solvent accessibility), particularly the mbondi2 set, since we typically use those to make the PQR files. In fact, probably the best way to get those radii is straight from a PQR file after running "ambpdb" on the prmtop and inpcrd files.

Does that answer your question?

**Comment by bensebaer** [comment]
Yes it does. I was looking at different ionic radii in the literature but couldn't find the exact ones you used and wanted to make sure whether I have the correct radii.

Thank you very much again for your help, I really appreciate it!
